FROM node:18 AS builder
RUN yarn policies set-version 4.1.1
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN npm install yarn --global --force
RUN yarn install

COPY . ./
RUN yarn install --immutable
RUN yarn build:react-vite

FROM nginx:1.19.0
COPY ./nginx/vite.conf /etc/nginx/conf.d/default.conf
RUN rm -rf ./usr/share/nginx/html/*
COPY --from=builder /app/apps/react-vite/dist /usr/share/nginx/html/
EXPOSE 3000
ENTRYPOINT ["nginx", "-g", "daemon off;"]